from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any, Dict, Optional

import pandas as pd


def _to_int(value: Any) -> Optional[int]:
    if value is None:
        return None
    if isinstance(value, bool):
        return int(value)
    try:
        return int(float(str(value).strip()))
    except (TypeError, ValueError):
        return None


def _to_float(value: Any, default: float = 0.0) -> float:
    try:
        return float(value)
    except (TypeError, ValueError):
        return default


def _to_bool(value: Any) -> bool:
    if isinstance(value, bool):
        return value
    s = str(value).strip().lower()
    return s in {"1", "true", "yes"}


def load_predictions(path: Path) -> pd.DataFrame:
    if not path.exists():
        raise FileNotFoundError(f"Predictions file not found: {path}")
    df = pd.read_csv(path)
    required = {
        "event_id",
        "match_id",
        "team_name",
        "player_name",
        "minute",
        "second",
        "decision",
        "decisionValue",
        "pred_pass",
        "pred_shot",
        "pred_carry",
        "bestDecisionType",
        "bestDecisionValue",
        "potentialGain",
        "suggestedAlternative",
        "isLowDecision",
    }
    missing = sorted(required - set(df.columns))
    if missing:
        raise ValueError(f"Missing columns in predictions CSV: {', '.join(missing)}")

    df["event_id_int"] = df["event_id"].apply(_to_int)
    df["minute_int"] = df["minute"].apply(_to_int)
    df["second_int"] = df["second"].apply(_to_int)
    df["match_id_str"] = df["match_id"].astype(str)
    return df


def filter_candidates(
    df: pd.DataFrame,
    event_id: Optional[int],
    match_id: Optional[str],
    minute: Optional[int],
    second: Optional[int],
    player_name: Optional[str],
    team_name: Optional[str],
) -> pd.DataFrame:
    filtered = df.copy()

    if event_id is not None:
        filtered = filtered[filtered["event_id_int"] == event_id]
    if match_id is not None:
        filtered = filtered[filtered["match_id_str"] == str(match_id)]
    if minute is not None:
        filtered = filtered[filtered["minute_int"] == minute]
    if second is not None:
        filtered = filtered[filtered["second_int"] == second]
    if player_name is not None:
        filtered = filtered[filtered["player_name"].astype(str).str.lower() == player_name.lower()]
    if team_name is not None:
        filtered = filtered[filtered["team_name"].astype(str).str.lower() == team_name.lower()]

    return filtered


def row_to_phase_output(row: pd.Series) -> Dict[str, Any]:
    actual_decision = str(row["decision"])
    actual_value = _to_float(row["decisionValue"])

    alternatives = [
        {"decision": "pass", "predictedValue": _to_float(row["pred_pass"])},
        {"decision": "shot", "predictedValue": _to_float(row["pred_shot"])},
        {"decision": "carry", "predictedValue": _to_float(row["pred_carry"])},
    ]
    alternatives = sorted(alternatives, key=lambda x: x["predictedValue"], reverse=True)

    best_decision = str(row["bestDecisionType"])
    best_value = _to_float(row["bestDecisionValue"])
    gain = _to_float(row["potentialGain"])
    suggested = row["suggestedAlternative"]
    suggested_decision = None if pd.isna(suggested) else str(suggested)
    low_decision = _to_bool(row["isLowDecision"])

    if best_decision == actual_decision or gain <= 0:
        insight = "Decizia reala este estimata ca fiind cea mai buna pentru aceasta faza."
    else:
        insight = (
            f"Modelul estimeaza ca '{best_decision}' era o decizie mai buna decat '{actual_decision}' "
            f"(+{gain:.4f} probabilitate de pericol)."
        )

    return {
        "eventId": _to_int(row["event_id"]),
        "matchId": str(row["match_id"]),
        "teamName": str(row["team_name"]),
        "playerName": str(row["player_name"]),
        "minute": _to_int(row["minute"]),
        "second": _to_int(row["second"]),
        "actualDecision": actual_decision,
        "actualDecisionValue": actual_value,
        "isLowDecision": low_decision,
        "suggestedAlternative": suggested_decision,
        "bestDecision": best_decision,
        "bestDecisionValue": best_value,
        "potentialGain": gain,
        "alternatives": alternatives,
        "insight": insight,
    }


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Get best decision recommendation for a specific phase/event.")
    parser.add_argument(
        "--predictions-csv",
        type=Path,
        default=Path("u_cluj_decision_quality_event_predictions.csv"),
        help="Path to event-level prediction CSV generated by decision_quality_pipeline.py",
    )
    parser.add_argument("--event-id", type=int, default=None, help="Exact event_id (preferred).")
    parser.add_argument("--match-id", type=str, default=None, help="Filter by match_id.")
    parser.add_argument("--minute", type=int, default=None, help="Filter by minute.")
    parser.add_argument("--second", type=int, default=None, help="Filter by second.")
    parser.add_argument("--player-name", type=str, default=None, help="Filter by exact player name.")
    parser.add_argument("--team-name", type=str, default=None, help="Filter by exact team name.")
    parser.add_argument(
        "--index",
        type=int,
        default=0,
        help="If multiple rows match, choose row by index after sorting by potential gain descending.",
    )
    parser.add_argument("--pretty", action="store_true", help="Pretty-print JSON.")
    return parser


def main() -> None:
    args = build_parser().parse_args()
    df = load_predictions(args.predictions_csv)

    candidates = filter_candidates(
        df=df,
        event_id=args.event_id,
        match_id=args.match_id,
        minute=args.minute,
        second=args.second,
        player_name=args.player_name,
        team_name=args.team_name,
    )

    if len(candidates) == 0:
        raise SystemExit(
            "No matching phase found. Use --event-id or provide enough filters "
            "(e.g. --match-id --minute --second --player-name)."
        )

    candidates = candidates.sort_values(["potentialGain", "decisionValue"], ascending=[False, True]).reset_index(drop=True)
    if args.index < 0 or args.index >= len(candidates):
        raise SystemExit(f"Invalid --index {args.index}. Matching rows available: {len(candidates)}")

    selected = candidates.iloc[args.index]
    output = row_to_phase_output(selected)
    output["matchedRows"] = int(len(candidates))
    output["selectedIndex"] = int(args.index)

    if args.pretty:
        print(json.dumps(output, ensure_ascii=False, indent=2))
    else:
        print(json.dumps(output, ensure_ascii=False))


if __name__ == "__main__":
    main()
